### ISSUE TITLE
Switch to this repository

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/collaborative-lesson-development#1]
Please edit this PR and fill in the `[]` beside your name when you have forked this repository.

- [x] Gabriel A. Devenyi
- [ ] Rémi Emonet
- [x] Rayna Harris
- [x] Kate Hertweck
- [x] Damien Irving
- [x] Ian Milligan
- [X] Greg Wilson

**Comment by DamienIrving** [comment]
Forked :-)

**Comment by ianmilligan1** [comment]
Forked on my end too!

**Comment by gdevenyi** [comment]
Forked, but I can't edit the issue.
