### ISSUE TITLE
Double check for jargon

### ISSUE THREAD

**Issue by k8hertweck** [swcarpentry/collaborative-lesson-development#10]
In the interest of attracting varied audiences to this article, I want us to be sure we double (and even triple) check for excessive jargon (related to both programming and education). One term that comes to mind is "forking."

**Comment by raynamharris** [comment]
Hmm. We are aim for PLOS Computational Biology, so I imagine the primary readership is Git aware, but I do agree that it might be worth being more descriptive when saying "GitHub issues" and "Version control" as these are not standard practices for our audiences outside computer science.
