### ISSUE TITLE
Figures and other 10 simple rules papers

### ISSUE THREAD

**Issue by k8hertweck** [swcarpentry/collaborative-lesson-development#12]
I can't find where Fig 1 is cited in the manuscript text (although I see where it's placed relative to the text?), but I'm also a total LaTeX noob. 

At one point, Rayna had mentioned another figure (Fig 2?) which compared traditional publication to the model we emphasize. This would be a great way to help connect our paper to some of the other 10 Simple Rules papers, such as the one on [preprints](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005473).

While we're thinking about it, some of the content from the 10 simple rules paper on  [MOOCs](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005061) may be relevant?

**Comment by raynamharris** [comment]
I'd think it would be fun to have a white board drawing discussion to hash out a figure two comparing the different schemas. I'd be happy to chat on Google Hangouts one day next week if you want to draw out a sketch together at the same time.

**Comment by raynamharris** [comment]
When is good to discuss figure on google hangouts:  http://whenisgood.net/b24csrf

**Comment by gvwilson** [comment]
Figure moved to end of paper in #27 because reasons.

**Comment by k8hertweck** [comment]
@raynamharris and I spent some time this morning thinking about another figure modeling an example process for collaborative development. You can view this figure [here](https://docs.google.com/drawings/d/1TsZfTUDkjGmffNHUDXdK7I_BtlKf1k-c6B6wHnqx8VQ/edit?usp=sharing); comments are welcome.

**Comment by gvwilson** [comment]
I like it! Suggestions:

- "recruit community" and "teach and mentor" should be connected
- "representing complete version": maybe "stable" instead of "complete", since they're never really complete
- somewhere (box? labelled arrow?) say that because the materials are being updated, they draw in new community members - that's what makes this self-sustaining (we hope)

:+1:

**Comment by ianmilligan1** [comment]
This looks fantastic to me! 

(apologies on my bout of radio silence, btw, I've co-organized events last week and this week on two different continents, so burning the candle at both ends)

**Comment by gdevenyi** [comment]
Absolutely love the figure :+1:

**Comment by k8hertweck** [comment]
Thanks folks, I've accommodated Greg's comments above and will add it to the repo.
