### ISSUE TITLE
Auto-generate PDF or text on website?

### ISSUE THREAD

**Issue by marwahaha** [swcarpentry/collaborative-lesson-development#17]
Hi!

I'm very fascinated by this paper. I find the guiding principles so compelling. 

As changes to this document come in, can the PDF be auto-generated? Or, could we have the text auto-generate onto a website somewhere (maybe using gh-pages)? It'd be useful to read this document in its latest form. 

You all rock!!

**Comment by marwahaha** [comment]
Although, I suppose a periodic release would be more in line with this paper :)

**Comment by gvwilson** [comment]
Judging from recent experience, PLOS is going to take our LaTeX and translate it into Word, at which point they will mangle the formatting of every second or third line. Our attempts to un-mangle it will be frustrated by their choice of a fixed-with font that doesn't preserve inter-word spacing, and by their insistence on using hanging indents in code samples (no, I'm not kidding). I'm therefore reluctant to invest much effort in connecting Travis-CI or the like to auto-generate the PDFs...

Why is academic publishing so broken??
