### ISSUE TITLE
Learning objectives?

### ISSUE THREAD

**Issue by bsmith89** [swcarpentry/collaborative-lesson-development#31]
I believe that the brief discussion of learning objectives could be amended.  Currently (585977c) learning objectives / concept inventories / etc. are covered first in the section for Rule 1:

> Rather than itemizing prior knowledge and learning objectives, it can be helpful to
> write learner profiles to clarify the learner’s general background, what they already
> know, what they think they want to do, how the material will help them, and any
> special needs they might have.

I'm a little bit surprised, since this seems to be recommending _against_ explicit learning objectives, while the section for Rule 4 includes:

> An example of a particular lesson development practice is reverse instructional
> design [2]. When this is used, lessons are built by identifying learning objectives,
> creating summative assessments to determine whether those objectives have been met,
> designing formative assessments to gauge learners’ progress and give them a chance to
> practice key skills, putting those formative assessments in order, and only then writing
> lessons to connect each to the next. This method is effective in its own right, but its
> greatest benefit is that it gives everyone a common framework within which to
> collaborate.

which is pretty clear on the benefits of such objectives.

I find explicit learning objectives to be beneficial in relation to many of the rules here, and could see them as a common thread throughout much of this paper.

**Rule 1**: Learning objectives help define the audience.  Learners who have already achieved many/all of the objectives are too advanced.  Learners who are not prepared to achieve them need additional background from other lessons.

**Rule 3**: Learning objectives promote modularity.  Independent modules have non-overlapping objectives and the material is designed to achieve those objectives (given appropriate learner background).

**Rule 4**: As described above, learning objectives lend themselves to a best practices in lesson development and provide a "common framework" for collaboration.

**Rule 7**: Learning objectives provide a framework for lesson assessment.  Are objectives appropriate?  Is the material successful at teaching to the objectives?

Apologies for suggesting the addition of content without suggesting what to replace.  If this is a major issue, I could imagine combining/condensing rules 3 and 8, and adding use of learning objectives as one of the 10 rules.

**Comment by raynamharris** [comment]
Thanks @bsmith89! These are great suggestions, and I think we can clarify the language to indicate that you need both learner profiles and learning objectives instead of one or the other. And, you're suggestions are spot of for how clear learning objectives provide a framework for subsequent steps in lesson development.
