### ISSUE TITLE
Christian T. Jacobs <C.T.Jacobs@soton.ac.uk> feedback

### ISSUE THREAD

**Issue by gdevenyi** [swcarpentry/collaborative-lesson-development#36]
Hi everyone,

I saw the link to your draft paper on the SWC Newsletter. I found it to be a very interesting read and in good shape. One piece of feedback that you may wish to take onboard:

In Section 4 it might be worth mentioning that, in addition to a collaboration tool's steep learning curve, the use of certain file formats and embedded images can further complicate pre-merge review. For example, we found (Git-tracked) IPython Notebook material to work very well when developing an undergrad programming course for geoscientists, but we often had to address time-consuming merge conflicts (both for the lecturers and the students) caused by e.g. re-running a piece of embedded Python code that updated an embedded plot/image, or using a more recent version of Notebook which caused small changes in header info, etc, and then merging/pulling:

"Additionally, in 2013, the IPython Notebook format was adopted (see above). The Git version control system was used in an attempt to apply any updates/corrections to the lecture notes as gracefully as possible, and also gave the students an insight into using version control to manage their work. However, this turned out to be somewhat counterproductive as merge conflicts frequently had to be resolved manually by the teaching assistants, which lowered the confidence the students had in the system they were using and added to the number of commands the students had to remember to download the latest revision of the lecture material. The majority of students in the class struggled to cope with both Linux and Git, which were both completely new to them."
http://dx.doi.org/10.5408/15-101.1 , https://arxiv.org/abs/1505.05425

Perhaps add a note to encourage readers to keep this in mind?

Hope this helps.

Kind regards,
Christian

**Comment by k8hertweck** [comment]
Thanks for transferring this message to a PR. This is an awesome citation we should add (assigning myself to make sure it happens)
