### ISSUE TITLE
Abstract is too brief

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/collaborative-lesson-development#44]
The abstract is currently too short to be very useful.

**Comment by DamienIrving** [comment]
I think that second bit - "the authors could do a better job..." - actually refers to the entire paper, not just the abstract. Hence, I've created #47 and removed it from this issue.

**Comment by DamienIrving** [comment]
I think the main problem here is that we have both an abstract and an author summary, both of which appear right after one another on the page (and hence to avoid repetition the abstract is super short). 

My suggested solution would be to remove the author summary and just work the text into the abstract. The author summary is meant to be a non-technical summary of the work, but our paper isn't technical and so it isn't really required.
