### ISSUE TITLE
Figures aren't used

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/collaborative-lesson-development#45]
Aside from their parenthetical mention at the end of the Introduction, neither of the figures is referred to in the main set of rules. I am not sure if both of these are necessary. Figure two, especially, encompasses a number of rather complex ideas about community building and lesson development that are not directly discussed at any length within the text. The second figure seems the more useful of the two, but in any event, I think both warrant more attention in the text or in captions if they are to be kept.

**Comment by raynamharris** [comment]
My intent for figure 1 was to provide a graphical abstract or a concise summary captures the content of the article in a single glance. I think it serves its purpose well.

I don't think that referencing fig 1 more within the body would improve the paper.  
I do agree that an elaboration of the caption would improve the paper.

So, unless anyone objects, I'll add a caption to fig1.

**Comment by ianmilligan1** [comment]
That was my understanding of Figure 1 as well, @raynamharris, so adding a captain sounds good. I think a parenthetical introduction at the end of the introductory section is sufficient.

**Comment by k8hertweck** [comment]
Figure 2 should be referenced at other points in the manuscript. Now that I've updated the figure (see #49 ) I can take a look at other places to reference it. 

It just occurred to me that I don't know where to include the caption. Should this be included with the figure itself, or as a legend someplace in the manuscript?

**Comment by raynamharris** [comment]
@k8hertweck "Figure captions are inserted immediately after the first paragraph in which the figure is cited. Figure files are uploaded separately."

**Comment by raynamharris** [comment]
Closing this issue now
