### ISSUE TITLE
Reorganize the section "Build community around lessons"

### ISSUE THREAD

**Issue by omsai** [swcarpentry/collaborative-lesson-development#5]
I enjoyed reading [the d68fede version](/swcarpentry/collaborative-lesson-development/tree/d68fede) of the manuscript.  Step 2 of "building community around lessons" introduces the challenges of keeping lessons up to date and working online.  The feeling I had reading that section that early on in the paper was those two points seem a little nuanced and might fit better if merged with step 5, "encourage and empower contributors"; sections 3 and 4 provide more concrete strategies to serve the community.

The title also seems very similar to step 5.  How different is building an online community to encouraging contributors?

I'm tempted to think that building an online community is more of a product of reaching the right people who have similar goals and experiences teaching the material in question, and who can give constructive feedback.  To manage finding a community like that online, one would probably need to bootstrap off of another established community.  For example, 2 years ago I had a conversation with a UW Madison student who mentioned coding bootcamp workshops taught by their local Hacker Within group.  So it would be interesting to read suggestions about allies to seek out.  Encouraging thinking beyond the need to satisfy one own's itch and find a teaching community could lead into the next point of building modular lessons.

**Comment by gvwilson** [comment]
See #85.
