### ISSUE TITLE
Reviewer Response Letter

### ISSUE THREAD

**Issue by ianmilligan1** [swcarpentry/collaborative-lesson-development#52]
I have put a rough draft of the reviewer response up here in markdown format.

https://github.com/swcarpentry/collaborative-lesson-development/blob/master/reviewer-response.md

Revisions, comments, etc. _greatly_ appreciated. The one area where I didn't think we had a full response for them was to this one:

>I find Tip #3 a bit difficult to digest. The flow of the narrative becomes a bit cloudy when it turns into a 5-point lesson within the 10-point document. A reference has been made to a different publication, which should help - but a bit more clarity on how this collection of five points become "best practices" is necessary. Perhaps a paragraph that more clearly states the important content the authors extracted from Wiggins and McTighe and how they used them to develop these "best practices" would be easier to understand.

I did some hand-waving but any additional thoughts on that?

**Comment by DamienIrving** [comment]
@ianmilligan1 Thanks for taking on this task - you've done a great job.

I've submitted a PR (#54) to try and address the comment about tip 3. In summary, I think it's good to talk about the Wiggins and McTighe approach to give a concrete example of a best practice that we teach and try to follow, but I agree that having a 1-5 list embedded in a larger 1-10 list is a little confusing, so I've rewritten the 1-5 list in paragraph form.

**Comment by gvwilson** [comment]
Please give a thumbs-up if you think we're ready to ship.

**Comment by DamienIrving** [comment]
I just gave a thumbs up, but here's a very minor fix that won't require everyone to re-thumbs up. #55

**Comment by raynamharris** [comment]
I've been wanting to elaborator on the build community rule for a while, but I just now got around to it. If you think my additions are unnecessary or distracting (since they weren't requested by reviewers), feel free decline the pull requests.

**Comment by gvwilson** [comment]
OK folks - submitting.  Thank you all for all your hard work.
