### ISSUE TITLE
mention code of code conduct

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/collaborative-lesson-development#58]
Rule 3 has a paragraph on the Programming Historian omnibus person, so I thought it would make sense to add a brief mention of the SWC/DC code of conduct.

**Comment by raynamharris** [comment]
Software Carpentry operates by a Code of Conduct that outlines acceptable standards of behavior for our community members and those interacting with the Carpentries at in-person events and in virtual spaces. Community members on a 'Policy Subcommittee' serve as advocates for the CoC and adjudicate reported Code of Conduct violations. Together, the Code of Conduct and the Policy Subcommittee help ensure that all members of the community are treated with respect.

**Comment by ianmilligan1** [comment]
👍
