### ISSUE TITLE
Management

### ISSUE THREAD

**Issue by drjwbaker** [swcarpentry/collaborative-lesson-development#6]
Great paper. I think needs something on management. Library Carpentry uses a maintainer model for its lessons, and - for me - the crucial aspect of this role is to ensure:

1) That the lesson doesn't suffer from bloat (because many authors make for bloaty writing), and
2) That discussions that have been had and rejected don't get had again (that is, they remember what the closed issues are).

In a way this is a partner to section '4 Teach best practices for lesson development'. That is, teaching best practice is one thing, but it means nothing if no-one is there to ensure that best practice is applied. Perhaps it fits in section '5 Encourage and empower contributors' in that we are talking about giving some contributors a sense of ownership, a specific and defined role in managing the ongoing development of a lesson, and credit for that work (which you don't mention at all, I think..)

I'm happy to help write this (depending on your timescales!)

**Comment by gdevenyi** [comment]
Hi @drjwbaker 

We cover credit in "6 Publish periodically and recognize contributions".

Indeed the notes prior to writing this draft did include a suggestion to document common discussions/disagreements so they don't happen regularly.

As for bloat, while it may be useful to discuss, do we have any evidence that many writers make for bloaty writing, perhaps a reference would help?

**Comment by drjwbaker** [comment]
Apologies, you do mention credit. I still think the role of maintainers is underplayed. You say maintaining is essential (first line). You say that maintenance is collaborative. You don't really specify what maintaining is beyond authoring + developing. 

On bloat, in terms of 'evidence', not my area. I just experience it all that time.. Anyway, I thought there was something in https://arxiv.org/pdf/1307.5448.pdf as @gvwilson & I had chatted about this once with respect to SWC, but I must have been dreaming!
