### ISSUE TITLE
in defence of git

### ISSUE THREAD

**Issue by tompollard** [swcarpentry/collaborative-lesson-development#7]
Interesting article, thanks for sharing. The comment about git being "a famously user-hostile tool" seems a little harsh, I thought. It has a steep learning curve for sure, and some functionality that I struggle to get my head around, but "hostile" is a strong word! The comment feels like it deserves a citation or some explanation at least.

**Comment by k8hertweck** [comment]
Thanks for the suggestion; I concur!
